/* eslint-disable import/prefer-default-export */
export const sidebarMockStore = {
  models: {
    coursewareMeta: {
      'course-v1:edX+DemoX+Demo_Course': {
        accessExpiration: null,
        canShowUpgradeSock: false,
        contentTypeGatingEnabled: false,
        courseGoals: {
          selectedGoal: null,
          weeklyLearningGoalEnabled: false,
        },
        id: 'course-v1:edX+DemoX+Demo_Course',
        title: 'Demonstration Course',
        offer: null,
        enrollmentStart: '2013-02-05T00:00:00Z',
        enrollmentEnd: null,
        end: null,
        start: '2013-02-05T05:00:00Z',
        enrollmentMode: null,
        isEnrolled: false,
        license: null,
        userTimezone: null,
        showCalculator: false,
        notes: {
          enabled: false,
          visible: true,
        },
        marketingUrl: null,
        celebrations: {
          firstSection: false,
          streakLengthToCelebrate: null,
          streakDiscountEnabled: false,
          weeklyGoal: false,
        },
        userHasPassingGrade: false,
        courseExitPageIsActive: false,
        certificateData: null,
        entranceExamData: {
          entranceExamCurrentScore: 0,
          entranceExamEnabled: false,
          entranceExamId: '',
          entranceExamMinimumScorePct: 0.65,
          entranceExamPassed: true,
        },
        timeOffsetMillis: -186,
        verifyIdentityUrl: null,
        verificationStatus: 'none',
        linkedinAddToProfileUrl: null,
        relatedPrograms: null,
        userNeedsIntegritySignature: false,
        canAccessProctoredExams: false,
        sectionIds: [
          'block-v1:edX+DemoX+Demo_Course+type@chapter+block@d8a6192ade314473a78242dfeedfbf5b',
          'block-v1:edX+DemoX+Demo_Course+type@chapter+block@interactive_demonstrations',
          'block-v1:edX+DemoX+Demo_Course+type@chapter+block@graded_interactions',
          'block-v1:edX+DemoX+Demo_Course+type@chapter+block@social_integration',
          'block-v1:edX+DemoX+Demo_Course+type@chapter+block@1414ffd5143b4b508f739b563ab468b7',
        ],
        hasScheduledContent: false,
      },
    },
    courseHomeMeta: {
      'course-v1:edX+DemoX+Demo_Course': {
        id: 'course-v1:edX+DemoX+Demo_Course',
        canShowUpgradeSock: false,
        verifiedMode: null,
        celebrations: {
          firstSection: false,
          streakLengthToCelebrate: null,
          streakDiscountEnabled: false,
          weeklyGoal: false,
        },
        courseAccess: {
          hasAccess: true,
          errorCode: null,
          developerMessage: null,
          userMessage: null,
          additionalContextUserMessage: null,
          userFragment: null,
        },
        courseId: 'course-v1:edX+DemoX+Demo_Course',
        isEnrolled: false,
        isSelfPaced: false,
        isStaff: true,
        number: 'DemoX',
        org: 'edX',
        originalUserIsStaff: true,
        start: '2013-02-05T05:00:00Z',
        tabs: [
          {
            slug: 'courseware',
            title: 'Course',
            url: 'http://apps.local.overhang.io/learning/course/course-v1:edX+DemoX+Demo_Course/home',
          },
          {
            slug: 'progress',
            title: 'Progress',
            url: 'http://apps.local.overhang.io/learning/course/course-v1:edX+DemoX+Demo_Course/progress',
          },
          {
            slug: 'instructor',
            title: 'Instructor',
            url: 'http://local.overhang.io/courses/course-v1:edX+DemoX+Demo_Course/instructor',
          },
        ],
        title: 'Demonstration Course',
        username: 'staff',
        userTimezone: null,
        canViewCertificate: false,
        isMasquerading: false,
      },
    },
    sections: {
      'block-v1:edX+DemoX+Demo_Course+type@chapter+block@d8a6192ade314473a78242dfeedfbf5b': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@chapter+block@d8a6192ade314473a78242dfeedfbf5b',
        title: 'Introduction',
        sequenceIds: [
          'block-v1:edX+DemoX+Demo_Course+type@sequential+block@edx_introduction',
        ],
        courseId: 'course-v1:edX+DemoX+Demo_Course',
      },
      'block-v1:edX+DemoX+Demo_Course+type@chapter+block@interactive_demonstrations': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@chapter+block@interactive_demonstrations',
        title: 'Example Week 1: Getting Started',
        sequenceIds: [
          'block-v1:edX+DemoX+Demo_Course+type@sequential+block@19a30717eff543078a5d94ae9d6c18a5',
          'block-v1:edX+DemoX+Demo_Course+type@sequential+block@basic_questions',
        ],
        courseId: 'course-v1:edX+DemoX+Demo_Course',
      },
      'block-v1:edX+DemoX+Demo_Course+type@chapter+block@graded_interactions': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@chapter+block@graded_interactions',
        title: 'Example Week 2: Get Interactive',
        sequenceIds: [
          'block-v1:edX+DemoX+Demo_Course+type@sequential+block@simulations',
          'block-v1:edX+DemoX+Demo_Course+type@sequential+block@graded_simulations',
          'block-v1:edX+DemoX+Demo_Course+type@sequential+block@175e76c4951144a29d46211361266e0e',
        ],
        courseId: 'course-v1:edX+DemoX+Demo_Course',
      },
      'block-v1:edX+DemoX+Demo_Course+type@chapter+block@social_integration': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@chapter+block@social_integration',
        title: 'Example Week 3: Be Social',
        sequenceIds: [
          'block-v1:edX+DemoX+Demo_Course+type@sequential+block@48ecb924d7fe4b66a230137626bfa93e',
          'block-v1:edX+DemoX+Demo_Course+type@sequential+block@dbe8fc027bcb4fe9afb744d2e8415855',
          'block-v1:edX+DemoX+Demo_Course+type@sequential+block@6ab9c442501d472c8ed200e367b4edfa',
        ],
        courseId: 'course-v1:edX+DemoX+Demo_Course',
      },
      'block-v1:edX+DemoX+Demo_Course+type@chapter+block@1414ffd5143b4b508f739b563ab468b7': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@chapter+block@1414ffd5143b4b508f739b563ab468b7',
        title: 'About Exams and Certificates',
        sequenceIds: [
          'block-v1:edX+DemoX+Demo_Course+type@sequential+block@workflow',
        ],
        courseId: 'course-v1:edX+DemoX+Demo_Course',
      },
    },
    sequences: {
      'block-v1:edX+DemoX+Demo_Course+type@sequential+block@edx_introduction': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@edx_introduction',
        title: 'Demo Course Overview',
        sectionId: 'block-v1:edX+DemoX+Demo_Course+type@chapter+block@d8a6192ade314473a78242dfeedfbf5b',
        blockType: 'sequential',
        unitIds: [
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_0270f6de40fc',
        ],
        bannerText: null,
        format: null,
        gatedContent: {
          prereqId: null,
          prereqUrl: null,
          prereqSectionName: null,
          gated: false,
          gatedSectionName: 'Demo Course Overview',
        },
        isTimeLimited: false,
        isProctored: false,
        isHiddenAfterDue: false,
        activeUnitIndex: 0,
        saveUnitPosition: true,
        showCompletion: true,
      },
      'block-v1:edX+DemoX+Demo_Course+type@sequential+block@19a30717eff543078a5d94ae9d6c18a5': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@19a30717eff543078a5d94ae9d6c18a5',
        title: 'Lesson 1 - Getting Started',
        sectionId: 'block-v1:edX+DemoX+Demo_Course+type@chapter+block@interactive_demonstrations',
        blockType: 'sequential',
        unitIds: [
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@867dddb6f55d410caaa9c1eb9c6743ec',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@4f6c1b4e316a419ab5b6bf30e6c708e9',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@3dc16db8d14842e38324e95d4030b8a0',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@4a1bba2a403f40bca5ec245e945b0d76',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@256f17a44983429fb1a60802203ee4e0',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@e3601c0abee6427d8c17e6d6f8fdddd1',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@a79d59cd72034188a71d388f4954a606',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@134df56c516a4a0dbb24dd5facef746e',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@d91b9e5d8bc64d57a1332d06bf2f2193',
        ],
        bannerText: null,
        format: null,
        gatedContent: {
          prereqId: null,
          prereqUrl: null,
          prereqSectionName: null,
          gated: false,
          gatedSectionName: 'Lesson 1 - Getting Started',
        },
        isTimeLimited: false,
        isProctored: false,
        isHiddenAfterDue: false,
        activeUnitIndex: 0,
        saveUnitPosition: true,
        showCompletion: true,
      },
      'block-v1:edX+DemoX+Demo_Course+type@sequential+block@basic_questions': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@basic_questions',
        title: 'Homework - Question Styles',
        sectionId: 'block-v1:edX+DemoX+Demo_Course+type@chapter+block@interactive_demonstrations',
        blockType: 'sequential',
        unitIds: [
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@2152d4a4aadc4cb0af5256394a3d1fc7',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@47dbd5f836544e61877a483c0b75606c',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@54bb9b142c6c4c22afc62bcb628f0e68',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_0c92347a5c00',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_1fef54c2b23b',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@2889db1677a549abb15eb4d886f95d1c',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@e8a5cc2aed424838853defab7be45e42',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@fb6b62dbec4348528629cf2232b86aea',
        ],
        bannerText: null,
        format: 'Homework',
        gatedContent: {
          prereqId: null,
          prereqUrl: null,
          prereqSectionName: null,
          gated: false,
          gatedSectionName: 'Homework - Question Styles',
        },
        isTimeLimited: false,
        isProctored: false,
        isHiddenAfterDue: false,
        activeUnitIndex: 0,
        saveUnitPosition: true,
        showCompletion: true,
      },
      'block-v1:edX+DemoX+Demo_Course+type@sequential+block@simulations': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@simulations',
        title: "Lesson 2 - Let's Get Interactive!",
        sectionId: 'block-v1:edX+DemoX+Demo_Course+type@chapter+block@graded_interactions',
        blockType: 'sequential',
        unitIds: [
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@d0d804e8863c4a95a659c04d8a2b2bc0',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_2dbb0072785e',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_98cf62510471',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_d32bf9b2242c',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@4e592689563243c484af947465eaef0d',
        ],
        bannerText: null,
        format: null,
        gatedContent: {
          prereqId: null,
          prereqUrl: null,
          prereqSectionName: null,
          gated: false,
          gatedSectionName: "Lesson 2 - Let's Get Interactive!",
        },
        isTimeLimited: false,
        isProctored: false,
        isHiddenAfterDue: false,
        activeUnitIndex: 0,
        saveUnitPosition: true,
        showCompletion: true,
      },
      'block-v1:edX+DemoX+Demo_Course+type@sequential+block@graded_simulations': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@graded_simulations',
        title: 'Homework - Labs and Demos',
        sectionId: 'block-v1:edX+DemoX+Demo_Course+type@chapter+block@graded_interactions',
        blockType: 'sequential',
        unitIds: [
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@d6cee45205a449369d7ef8f159b22bdf',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_aae927868e55',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_c037f3757df1',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_bc69a47c6fae',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@8f89194410954e768bde1764985454a7',
        ],
        bannerText: null,
        format: 'Homework',
        gatedContent: {
          prereqId: null,
          prereqUrl: null,
          prereqSectionName: null,
          gated: false,
          gatedSectionName: 'Homework - Labs and Demos',
        },
        isTimeLimited: false,
        isProctored: false,
        isHiddenAfterDue: false,
        activeUnitIndex: 0,
        saveUnitPosition: true,
        showCompletion: true,
      },
      'block-v1:edX+DemoX+Demo_Course+type@sequential+block@175e76c4951144a29d46211361266e0e': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@175e76c4951144a29d46211361266e0e',
        title: 'Homework - Essays',
        sectionId: 'block-v1:edX+DemoX+Demo_Course+type@chapter+block@graded_interactions',
        blockType: 'sequential',
        unitIds: [
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@fb79dcbad35b466a8c6364f8ffee9050',
        ],
        bannerText: null,
        format: null,
        gatedContent: {
          prereqId: null,
          prereqUrl: null,
          prereqSectionName: null,
          gated: false,
          gatedSectionName: 'Homework - Essays',
        },
        isTimeLimited: false,
        isProctored: false,
        isHiddenAfterDue: false,
        activeUnitIndex: 0,
        saveUnitPosition: true,
        showCompletion: true,
      },
      'block-v1:edX+DemoX+Demo_Course+type@sequential+block@48ecb924d7fe4b66a230137626bfa93e': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@48ecb924d7fe4b66a230137626bfa93e',
        title: 'Lesson 3 - Be Social',
        sectionId: 'block-v1:edX+DemoX+Demo_Course+type@chapter+block@social_integration',
        blockType: 'sequential',
        unitIds: [
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@3c4b575924bf4b75a2f3542df5c354fc',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_3888db0bc286',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@312cb4faed17420e82ab3178fc3e251a',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@7efc7bf4a47b4a6cb6595c32cde7712a',
        ],
        bannerText: null,
        format: null,
        gatedContent: {
          prereqId: null,
          prereqUrl: null,
          prereqSectionName: null,
          gated: false,
          gatedSectionName: 'Lesson 3 - Be Social',
        },
        isTimeLimited: false,
        isProctored: false,
        isHiddenAfterDue: false,
        activeUnitIndex: 0,
        saveUnitPosition: true,
        showCompletion: true,
      },
      'block-v1:edX+DemoX+Demo_Course+type@sequential+block@dbe8fc027bcb4fe9afb744d2e8415855': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@dbe8fc027bcb4fe9afb744d2e8415855',
        title: 'Homework - Find Your Study Buddy',
        sectionId: 'block-v1:edX+DemoX+Demo_Course+type@chapter+block@social_integration',
        blockType: 'sequential',
        unitIds: [
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@26d89b08f75d48829a63520ed8b0037d',
        ],
        bannerText: null,
        format: null,
        gatedContent: {
          prereqId: null,
          prereqUrl: null,
          prereqSectionName: null,
          gated: false,
          gatedSectionName: 'Homework - Find Your Study Buddy',
        },
        isTimeLimited: false,
        isProctored: false,
        isHiddenAfterDue: false,
        activeUnitIndex: 0,
        saveUnitPosition: true,
        showCompletion: true,
      },
      'block-v1:edX+DemoX+Demo_Course+type@sequential+block@6ab9c442501d472c8ed200e367b4edfa': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@6ab9c442501d472c8ed200e367b4edfa',
        title: 'More Ways to Connect',
        sectionId: 'block-v1:edX+DemoX+Demo_Course+type@chapter+block@social_integration',
        blockType: 'sequential',
        unitIds: [
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@3f2c11aba9434e459676a7d7acc4d960',
        ],
        bannerText: null,
        format: null,
        gatedContent: {
          prereqId: null,
          prereqUrl: null,
          prereqSectionName: null,
          gated: false,
          gatedSectionName: 'More Ways to Connect',
        },
        isTimeLimited: false,
        isProctored: false,
        isHiddenAfterDue: false,
        activeUnitIndex: 0,
        saveUnitPosition: true,
        showCompletion: true,
      },
      'block-v1:edX+DemoX+Demo_Course+type@sequential+block@workflow': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@workflow',
        title: 'edX Exams',
        sectionId: 'block-v1:edX+DemoX+Demo_Course+type@chapter+block@1414ffd5143b4b508f739b563ab468b7',
        blockType: 'sequential',
        unitIds: [
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@934cc32c177d41b580c8413e561346b3',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_f04afeac0131',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@b6662b497c094bcc9b870d8270c90c93',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@f91d8d31f7cf48ce990f8d8745ae4cfa',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_ac391cde8a91',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_36e0beb03f0a',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@1b0e2c2c84884b95b1c99fb678cc964c',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@c7e98fd39a6944edb6b286c32e1150ff',
          'block-v1:edX+DemoX+Demo_Course+type@vertical+block@d6eaa391d2be41dea20b8b1bfbcb1c45',
        ],
        bannerText: null,
        format: 'Exam',
        gatedContent: {
          prereqId: null,
          prereqUrl: null,
          prereqSectionName: null,
          gated: false,
          gatedSectionName: 'edX Exams',
        },
        isTimeLimited: false,
        isProctored: false,
        isHiddenAfterDue: false,
        activeUnitIndex: 0,
        saveUnitPosition: true,
        showCompletion: true,
      },
    },
    units: {
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@867dddb6f55d410caaa9c1eb9c6743ec': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@867dddb6f55d410caaa9c1eb9c6743ec',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@19a30717eff543078a5d94ae9d6c18a5',
        bookmarked: false,
        complete: true,
        title: 'Getting Started',
        contentType: 'other',
        graded: false,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@4f6c1b4e316a419ab5b6bf30e6c708e9': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@4f6c1b4e316a419ab5b6bf30e6c708e9',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@19a30717eff543078a5d94ae9d6c18a5',
        bookmarked: false,
        complete: false,
        title: 'Working with Videos',
        contentType: 'video',
        graded: false,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@3dc16db8d14842e38324e95d4030b8a0': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@3dc16db8d14842e38324e95d4030b8a0',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@19a30717eff543078a5d94ae9d6c18a5',
        bookmarked: false,
        complete: false,
        title: 'Videos on edX',
        contentType: 'video',
        graded: false,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@4a1bba2a403f40bca5ec245e945b0d76': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@4a1bba2a403f40bca5ec245e945b0d76',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@19a30717eff543078a5d94ae9d6c18a5',
        bookmarked: false,
        complete: true,
        title: 'Video Demonstrations',
        contentType: 'other',
        graded: false,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@256f17a44983429fb1a60802203ee4e0': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@256f17a44983429fb1a60802203ee4e0',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@19a30717eff543078a5d94ae9d6c18a5',
        bookmarked: false,
        complete: false,
        title: 'Video Presentation Styles',
        contentType: 'video',
        graded: false,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@e3601c0abee6427d8c17e6d6f8fdddd1': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@e3601c0abee6427d8c17e6d6f8fdddd1',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@19a30717eff543078a5d94ae9d6c18a5',
        bookmarked: false,
        complete: false,
        title: 'Interactive Questions',
        contentType: 'problem',
        graded: false,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@a79d59cd72034188a71d388f4954a606': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@a79d59cd72034188a71d388f4954a606',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@19a30717eff543078a5d94ae9d6c18a5',
        bookmarked: false,
        complete: false,
        title: 'Exciting Labs and Tools',
        contentType: 'other',
        graded: false,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@134df56c516a4a0dbb24dd5facef746e': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@134df56c516a4a0dbb24dd5facef746e',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@19a30717eff543078a5d94ae9d6c18a5',
        bookmarked: false,
        complete: false,
        title: 'Reading Assignments',
        contentType: 'problem',
        graded: false,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@d91b9e5d8bc64d57a1332d06bf2f2193': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@d91b9e5d8bc64d57a1332d06bf2f2193',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@19a30717eff543078a5d94ae9d6c18a5',
        bookmarked: false,
        complete: true,
        title: 'When Are Your Exams?',
        contentType: 'other',
        graded: false,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_0270f6de40fc': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_0270f6de40fc',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@edx_introduction',
        bookmarked: false,
        complete: false,
        title: 'Introduction: Video and Sequences',
        contentType: 'video',
        graded: false,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@2152d4a4aadc4cb0af5256394a3d1fc7': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@2152d4a4aadc4cb0af5256394a3d1fc7',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@basic_questions',
        bookmarked: false,
        complete: false,
        title: 'Pointing on a Picture',
        contentType: 'problem',
        graded: true,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@47dbd5f836544e61877a483c0b75606c': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@47dbd5f836544e61877a483c0b75606c',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@basic_questions',
        bookmarked: false,
        complete: false,
        title: 'Drag and Drop',
        contentType: 'problem',
        graded: true,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@54bb9b142c6c4c22afc62bcb628f0e68': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@54bb9b142c6c4c22afc62bcb628f0e68',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@basic_questions',
        bookmarked: false,
        complete: false,
        title: 'Multiple Choice Questions',
        contentType: 'problem',
        graded: true,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_0c92347a5c00': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_0c92347a5c00',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@basic_questions',
        bookmarked: false,
        complete: false,
        title: 'Mathematical Expressions',
        contentType: 'problem',
        graded: true,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_1fef54c2b23b': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_1fef54c2b23b',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@basic_questions',
        bookmarked: false,
        complete: false,
        title: 'Chemical Equations',
        contentType: 'problem',
        graded: true,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@2889db1677a549abb15eb4d886f95d1c': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@2889db1677a549abb15eb4d886f95d1c',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@basic_questions',
        bookmarked: false,
        complete: false,
        title: 'Numerical Input',
        contentType: 'problem',
        graded: true,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@e8a5cc2aed424838853defab7be45e42': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@e8a5cc2aed424838853defab7be45e42',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@basic_questions',
        bookmarked: false,
        complete: false,
        title: 'Text input',
        contentType: 'problem',
        graded: true,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@fb6b62dbec4348528629cf2232b86aea': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@fb6b62dbec4348528629cf2232b86aea',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@basic_questions',
        bookmarked: false,
        complete: false,
        title: 'Instructor Programmed Responses',
        contentType: 'problem',
        graded: true,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@d0d804e8863c4a95a659c04d8a2b2bc0': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@d0d804e8863c4a95a659c04d8a2b2bc0',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@simulations',
        bookmarked: false,
        complete: false,
        title: "Lesson 2 - Let's Get Interactive!",
        contentType: 'other',
        graded: false,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_2dbb0072785e': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_2dbb0072785e',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@simulations',
        bookmarked: false,
        complete: true,
        title: 'An Interactive Reference Table',
        contentType: 'other',
        graded: false,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_98cf62510471': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_98cf62510471',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@simulations',
        bookmarked: false,
        complete: false,
        title: 'Zooming Diagrams',
        contentType: 'other',
        graded: false,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_d32bf9b2242c': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_d32bf9b2242c',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@simulations',
        bookmarked: false,
        complete: false,
        title: 'Electronic Sound Experiment',
        contentType: 'other',
        graded: false,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@4e592689563243c484af947465eaef0d': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@4e592689563243c484af947465eaef0d',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@simulations',
        bookmarked: false,
        complete: false,
        title: 'New Unit',
        contentType: 'video',
        graded: false,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@d6cee45205a449369d7ef8f159b22bdf': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@d6cee45205a449369d7ef8f159b22bdf',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@graded_simulations',
        bookmarked: false,
        complete: false,
        title: 'Labs and Demos',
        contentType: 'other',
        graded: true,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_aae927868e55': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_aae927868e55',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@graded_simulations',
        bookmarked: false,
        complete: false,
        title: 'Code Grader',
        contentType: 'problem',
        graded: true,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_c037f3757df1': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_c037f3757df1',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@graded_simulations',
        bookmarked: false,
        complete: false,
        title: 'Electric Circuit Simulator',
        contentType: 'problem',
        graded: true,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_bc69a47c6fae': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_bc69a47c6fae',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@graded_simulations',
        bookmarked: false,
        complete: false,
        title: 'Protein Creator',
        contentType: 'problem',
        graded: true,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@8f89194410954e768bde1764985454a7': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@8f89194410954e768bde1764985454a7',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@graded_simulations',
        bookmarked: false,
        complete: false,
        title: 'Molecule Structures',
        contentType: 'problem',
        graded: true,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@fb79dcbad35b466a8c6364f8ffee9050': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@fb79dcbad35b466a8c6364f8ffee9050',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@175e76c4951144a29d46211361266e0e',
        bookmarked: false,
        complete: false,
        title: 'Peer Assessed Essays',
        contentType: 'problem',
        graded: false,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@3c4b575924bf4b75a2f3542df5c354fc': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@3c4b575924bf4b75a2f3542df5c354fc',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@48ecb924d7fe4b66a230137626bfa93e',
        bookmarked: false,
        complete: false,
        title: 'Be Social',
        contentType: 'other',
        graded: false,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_3888db0bc286': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_3888db0bc286',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@48ecb924d7fe4b66a230137626bfa93e',
        bookmarked: false,
        complete: false,
        title: 'Discussion Forums',
        contentType: 'other',
        graded: false,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@312cb4faed17420e82ab3178fc3e251a': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@312cb4faed17420e82ab3178fc3e251a',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@48ecb924d7fe4b66a230137626bfa93e',
        bookmarked: false,
        complete: false,
        title: 'Getting Help',
        contentType: 'other',
        graded: false,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@7efc7bf4a47b4a6cb6595c32cde7712a': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@7efc7bf4a47b4a6cb6595c32cde7712a',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@48ecb924d7fe4b66a230137626bfa93e',
        bookmarked: false,
        complete: false,
        title: 'Homework - Find Your Study Buddy',
        contentType: 'other',
        graded: false,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@26d89b08f75d48829a63520ed8b0037d': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@26d89b08f75d48829a63520ed8b0037d',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@dbe8fc027bcb4fe9afb744d2e8415855',
        bookmarked: false,
        complete: false,
        title: 'Homework - Find Your Study Buddy',
        contentType: 'other',
        graded: false,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@3f2c11aba9434e459676a7d7acc4d960': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@3f2c11aba9434e459676a7d7acc4d960',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@6ab9c442501d472c8ed200e367b4edfa',
        bookmarked: false,
        complete: false,
        title: 'Google Hangout',
        contentType: 'other',
        graded: false,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@934cc32c177d41b580c8413e561346b3': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@934cc32c177d41b580c8413e561346b3',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@workflow',
        bookmarked: false,
        complete: false,
        title: 'EdX Exams',
        contentType: 'other',
        graded: true,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_f04afeac0131': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_f04afeac0131',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@workflow',
        bookmarked: false,
        complete: false,
        title: 'Immediate Feedback',
        contentType: 'problem',
        graded: true,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@b6662b497c094bcc9b870d8270c90c93': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@b6662b497c094bcc9b870d8270c90c93',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@workflow',
        bookmarked: false,
        complete: false,
        title: 'Getting Answers',
        contentType: 'problem',
        graded: true,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@f91d8d31f7cf48ce990f8d8745ae4cfa': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@f91d8d31f7cf48ce990f8d8745ae4cfa',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@workflow',
        bookmarked: false,
        complete: false,
        title: 'Answering More Than Once',
        contentType: 'problem',
        graded: true,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_ac391cde8a91': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_ac391cde8a91',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@workflow',
        bookmarked: false,
        complete: false,
        title: 'Limited Checks',
        contentType: 'problem',
        graded: true,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_36e0beb03f0a': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_36e0beb03f0a',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@workflow',
        bookmarked: false,
        complete: false,
        title: 'Randomized Questions',
        contentType: 'problem',
        graded: true,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@1b0e2c2c84884b95b1c99fb678cc964c': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@1b0e2c2c84884b95b1c99fb678cc964c',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@workflow',
        bookmarked: false,
        complete: false,
        title: 'Overall Grade Performance',
        contentType: 'other',
        graded: true,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@c7e98fd39a6944edb6b286c32e1150ff': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@c7e98fd39a6944edb6b286c32e1150ff',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@workflow',
        bookmarked: false,
        complete: false,
        title: 'Passing a Course',
        contentType: 'other',
        graded: true,
        containsContentTypeGatedContent: false,
      },
      'block-v1:edX+DemoX+Demo_Course+type@vertical+block@d6eaa391d2be41dea20b8b1bfbcb1c45': {
        id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@d6eaa391d2be41dea20b8b1bfbcb1c45',
        sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@workflow',
        bookmarked: false,
        complete: false,
        title: 'Getting Your edX Certificate',
        contentType: 'other',
        graded: true,
        containsContentTypeGatedContent: false,
      },
    },
  },
  courseware: {
    courseStatus: 'loaded',
    courseId: 'course-v1:edX+DemoX+Demo_Course',
    sequenceStatus: 'loaded',
    sequenceId: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@19a30717eff543078a5d94ae9d6c18a5',
    sequenceMightBeUnit: false,
  },
  courseView: {
    isMobileSidebarOpen: false,
    isDesktopSidebarExtended: true,
  },
  sidebar: {
    collapsibleMenuState: {
      'block-v1:edX+DemoX+Demo_Course+type@chapter+block@d8a6192ade314473a78242dfeedfbf5b': false,
      'block-v1:edX+DemoX+Demo_Course+type@chapter+block@interactive_demonstrations': false,
      'block-v1:edX+DemoX+Demo_Course+type@chapter+block@graded_interactions': false,
      'block-v1:edX+DemoX+Demo_Course+type@chapter+block@social_integration': false,
      'block-v1:edX+DemoX+Demo_Course+type@chapter+block@1414ffd5143b4b508f739b563ab468b7': false,
      'block-v1:edX+DemoX+Demo_Course+type@sequential+block@edx_introduction': false,
      'block-v1:edX+DemoX+Demo_Course+type@sequential+block@19a30717eff543078a5d94ae9d6c18a5': false,
      'block-v1:edX+DemoX+Demo_Course+type@sequential+block@basic_questions': false,
      'block-v1:edX+DemoX+Demo_Course+type@sequential+block@simulations': false,
      'block-v1:edX+DemoX+Demo_Course+type@sequential+block@graded_simulations': false,
      'block-v1:edX+DemoX+Demo_Course+type@sequential+block@175e76c4951144a29d46211361266e0e': false,
      'block-v1:edX+DemoX+Demo_Course+type@sequential+block@48ecb924d7fe4b66a230137626bfa93e': false,
      'block-v1:edX+DemoX+Demo_Course+type@sequential+block@dbe8fc027bcb4fe9afb744d2e8415855': false,
      'block-v1:edX+DemoX+Demo_Course+type@sequential+block@6ab9c442501d472c8ed200e367b4edfa': false,
      'block-v1:edX+DemoX+Demo_Course+type@sequential+block@workflow': false,
    },
  },
};
